### PR TITLE
update to 4.19.0

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Looks good but could you please test it with the downstream packages `gnutls` AND `ffmpeg`?

**Comment by M-Waszkiewicz-Anaconda** [comment]
> Looks good but could you please test it with the downstream packages `gnutls` AND `ffmpeg`?

ok, dunno if I test it correctly, but what I did was:
- add to gnutls/-feedstock/receipe/meta.yaml the specific version for host libtasn1 dependency, changed from: `- libtasn1` to `- libtasn1 4.19.0`
- run `conda-build --use-local ./gnutls-feedstock`
gnutls build & test has passed.

For ffmpeg it does not have explicit reference to libtasn1 but only to gnults, so I build it and test also with use-local to use the locally gnutls build in previous step, 
this build also passed

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by akabanovs — APPROVED** [review]
LGTM

**Pull request merged**
